version: '3.9'
services:
  cacttus-core-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=PersonalDb
    ports:
      - '5432:5432'