spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/PersonalDb
    username: user
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
