-- Create the 'expenses' table
CREATE TABLE expenses (
                          id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_id BIGINT NOT NULL,
                          expenses DOUBLE PRECISION CHECK (expenses >= 0) NOT NULL,
                          purpose VARCHAR(255),
                          category VARCHAR(50) NOT NULL,
                          created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          date DATE CHECK (date >= '2020-01-01') NOT NULL,
                          CONSTRAINT FK_expenses_users_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);