-- Create the 'balances' table
CREATE TABLE balances (
                          id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_id BIGINT NOT NULL,
                          budget DOUBLE PRECISION CHECK (budget >= 0) NOT NULL,
                          source VARCHAR(255),
                          date DATE CHECK (date >= '2020-01-01') NOT NULL,
                          created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          CONSTRAINT FK_balances_users_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);